-- Seed the 7 atelier departments. Idempotent on slug.

insert into services (slug, icon_name, position, status, title_en, title_fr, summary_en, summary_fr, body_en, body_fr) values
('design', 'PenTool', 1, 'published',
 'Design', 'Conception',
 'Translating a brief into a precise blueprint.',
 'Traduire un brief en plan précis.',
 'Every commission opens with the design department. Hand sketches, CAD renders, and material swatches are produced until the brief is locked. We do not begin work on the watch until you have approved the file.',
 'Chaque réalisation commence au département conception. Croquis manuels, rendus CAO et échantillons matières sont produits jusqu''à validation du dossier. Aucun travail ne débute avant votre accord écrit.'),
('engraving', 'Sparkles', 2, 'published',
 'Hand Engraving', 'Gravure à la main',
 'Bezels, case-bands, lugs, dial details — engraved by hand.',
 'Lunettes, carrures, cornes, détails de cadran — gravés à la main.',
 'We do not subcontract engraving. A single master engraver carries each piece from rough cut to final finish. Lettering, scrolls, full Damascene grounds and bas-relief portraiture are all part of the repertoire.',
 'La gravure n''est jamais sous-traitée. Un seul maître graveur accompagne chaque pièce du dégrossi à la finition. Lettrage, volutes, fonds damasquinés et bas-reliefs font partie du répertoire.'),
('skeletonisation', 'Layers', 3, 'published',
 'Skeletonisation', 'Squelettage',
 'Reducing a movement to its essential structure.',
 'Réduire un mouvement à sa structure essentielle.',
 'Working from the original calibre we remove material along strict load paths, refinish bridges and plates, then anglage every visible edge. The watch keeps factory accuracy after our intervention or it does not leave the atelier.',
 'À partir du calibre d''origine, nous retirons matière selon des trajectoires de charge strictes, refinissons ponts et platines, puis anglons chaque arête visible. La précision d''origine est conservée — sans cela, la pièce ne sort pas de l''atelier.'),
('gem-setting', 'Gem', 4, 'published',
 'Gem-setting', 'Sertissage',
 'Snow, baguette, pavé, invisible — set in-house.',
 'Neige, baguette, pavé, invisible — sertis en interne.',
 'Stones are sourced from a small group of suppliers we trust on origin and certification. Setting is performed under microscope on the watch itself, never on a replacement part.',
 'Les pierres proviennent d''un cercle restreint de fournisseurs de confiance, sur origine et certification. Le sertissage s''effectue sous binoculaire sur la pièce elle-même, jamais sur un composant de remplacement.'),
('dial-making', 'CircleDot', 5, 'published',
 'Dial Making', 'Cadran',
 'New dials in enamel, lacquer, meteorite, hand-guilloché.',
 'Cadrans neufs en émail, laque, météorite, guilloché main.',
 'We replace the dial only when the brief calls for it. Grand feu enamel, fired in our own kilns, is our signature; we also work in stone, mother-of-pearl, and full-aventurine.',
 'Nous ne remplaçons le cadran que si le brief l''exige. L''émail grand feu, cuit dans nos propres fours, est notre signature ; nous travaillons aussi pierres, nacre et aventurine.'),
('finishing', 'Hand', 6, 'published',
 'Finishing', 'Finition',
 'Côtes de Genève, perlage, anglage, black polish.',
 'Côtes de Genève, perlage, anglage, poli noir.',
 'Surface treatments are the quiet luxury of horology. Every visible surface — and many invisible ones — is finished by hand to a tolerance most owners never see and yet always feel.',
 'Les traitements de surface sont le luxe discret de l''horlogerie. Chaque surface visible — et beaucoup d''invisibles — est finie main à une tolérance que peu remarquent mais que tous ressentent.'),
('restoration', 'Wrench', 7, 'published',
 'Restoration', 'Restauration',
 'Returning a vintage piece to running order, with respect.',
 'Remettre une pièce ancienne en marche, avec respect.',
 'Where commissions add, restoration preserves. We re-create lost components from period drawings, refinish without erasing the watchmaker''s original tool marks, and document every intervention.',
 'Là où la réalisation ajoute, la restauration préserve. Nous reproduisons les composants manquants d''après plans d''époque, refinissons sans effacer les marques d''outil d''origine, et documentons chaque intervention.')
on conflict (slug) do update set
  icon_name = excluded.icon_name,
  position = excluded.position,
  status = excluded.status,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  summary_en = excluded.summary_en,
  summary_fr = excluded.summary_fr,
  body_en = excluded.body_en,
  body_fr = excluded.body_fr;
